### ISSUE TITLE
Default black color of "others" in maps (e.g., health facility type or MoSD3 map) could not be changed to another color 

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#179]
There is a problem on changing the black color default of "others" in Health Facility Type (MoSD3) in HeRAMS NGA (id: 1, sort: 0 in overview; id: 8 and 9 in infrastructure) and PHL (id: 46, sort:0 in overview) despite several tries of changing it. 
<img width="1680" alt="Screen Shot 2019-08-19 at 10 54 35 PM" src="https://user-images.githubusercontent.com/50957748/63276061-3c7a9580-c2d5-11e9-9728-cff7adcbef34.png">
<img width="1680" alt="Screen Shot 2019-08-19 at 10 58 26 PM" src="https://user-images.githubusercontent.com/50957748/63276089-47cdc100-c2d5-11e9-9013-9b27770a331d.png">

**Comment by luna404** [comment]
I encountered the same problem with with Tchad (element id = 37) also using the MoSD3  variable. However, I was previously able to change the color for "Others" (e.g.[Mali, Vue d'ensemble](https://herams-staging.org/element/159/update)).

**Comment by luna404** [comment]
Same issue with charts (e.g. https://herams-staging.org/element/38/update).

**Comment by SamMousa** [comment]
I think this is resolved.

**Comment by JeffDotingco** [comment]
I still couldn't change the default black color of "others" for Health Facility Type (MoSD3)

**Comment by luna404** [comment]
This is fixed when you update a chart, but there is still an issue with colors being overwritten upon element creation #188.

**Comment by JeffDotingco** [comment]
Fixed in updating a chart but there is still an issue with maps

**Comment by SamMousa** [comment]
Can reproduce this, will look at it today.

**Comment by SamMousa** [comment]
Try now!

**Comment by luna404** [comment]
Tested for both charts and maps with difference question codes. Issue is resolved!

**Comment by SamuelPetragallo** [comment]
Bug confirmed here: there seem to be a reset of colors upon saving a new element for the first time. Weird, do you have an idea where that may come from @SamMousa ?

(I don't think it's needed for today's release)

**Comment by SamMousa** [comment]
So it is not fixed on staging @SamMousa ?

**Comment by JeffDotingco** [comment]
Still not working on staging and production. I checked this in staging for HeRAMS PHL and production for HeRAMS NGA.

**Comment by JeffDotingco** [comment]
Thanks @luna404 for opening the issue again because I can't open an issue from a closed one. As discussed from the previous comment, I still couldn't change the default black color of "others" in maps. Checked this on staging for HeRAMS PHL and production for HeRAMS NGA.

**Comment by JeffDotingco** [comment]
The changing of default black color of "others" is still not working upon checking today in Prod and Staging @SamMousa @SamuelPetragallo . I even have to change the code first of the map and return back the previous code (MoSD3) to check, still the same.

**Comment by jeremiehelme** [comment]
@SamMousa There is a difference in the key used for the value "Other"

The array of datas sent by an Element uses "-oth-", but the array of colors used in the Map widget uses "_oth_" as key. So it doesn't find the color and choose #000000 

Now, I don't know which one should be changed and where they are defined, so I let it to you :)
