### ISSUE TITLE
Tests failing on preprod

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#549]
Hello @SamMousa,

I'm having an issue with the tests on staging when I push changes.
They are successful on my machine, but some fail on staging

They all fail on $I->amOnPage and return the same error 

```
1) CreateCest: Test create root page
 Test  tests/functional/controllers/page/CreateCest.php:testCreateRootPage
                                                              
  [yii\base\ErrorException] Undefined index: constraint_name  
                                                              
Scenario Steps:

 5. $I->amOnPage({"0":"page/create","project_id":13}) at tests/functional/controllers/page/CreateCest.php:32
 4. $I->assertTrue(true,"Array\n(\n)\n") at tests/_support/FunctionalTester.php:58
 3. $I->amLoggedInAs(1) at tests/functional/controllers/page/CreateCest.php:30
 2. $I->assertFalse(false) at tests/functional/controllers/page/CreateCest.php:15
 1. $I->assertTrue(true) at tests/functional/controllers/page/CreateCest.php:14
```

What is strange is that they don't fail on my machine. 
I though I had to pull some changes from git, but it's up to date. 
I tried docker-compose run --rm cli migrate
I don't think rebuilding the modules is needed

I can't find "constraint_name" in the code. It makes me think of something related to the database ?

I don't know what to try next 
Thanks for your help,

Local
<img width="505" alt="Capture d’écran 2020-07-23 à 09 07 59" src="https://user-images.githubusercontent.com/2345926/88260288-60541180-ccc4-11ea-9802-893271b212e6.png">

Staging
![Capture d’écran 2020-07-23 à 09 08 30](https://user-images.githubusercontent.com/2345926/88260314-6a761000-ccc4-11ea-8ef0-0593927812af.png)

**Comment by SamMousa** [comment]
The tests are not run on staging; they are run on a clean CI system everytime.
You can try to remove everything locally to reproduce it:
1. Run `docker-compose pull` to pull any used images and `docker-compose build` to build any used images.
2. Run `docker-compose down` to remove all containers
3. Run the tests again, see if you can reproduce it locally.

**Comment by jeremiehelme** [comment]
Nice, thanks 
I'll try those steps next time

Now I have the same errors on my machine
They still fail with the same error message _Undefined index: constraint_name_

They all finish on _/project/vendor/yiisoft/yii2/db/mysql/Schema.php:394_

_/project/protected/models/ar/Page.php:37_ is just the initialization

Again, I'm not sure where to look next, sorry for the trouble...

```
8) ViewCest: Test view with page and read
 Test  tests/functional/controllers/project/ViewCest.php:testViewWithPageAndRead
                                                              
  [yii\base\ErrorException] Undefined index: constraint_name  
                                                              

Scenario Steps:

 2. $I->assertTrue(true,"Array\n(\n)\n") at tests/_support/FunctionalTester.php:58
 1. $I->amLoggedInAs(2) at tests/functional/controllers/project/ViewCest.php:35

#1  /project/vendor/yiisoft/yii2/db/mysql/Schema.php:394
#2  /project/vendor/yiisoft/yii2/db/mysql/Schema.php:126
#3  /project/vendor/yiisoft/yii2/db/Schema.php:754
#4  /project/vendor/yiisoft/yii2/db/Schema.php:193
#5  /project/vendor/yiisoft/yii2/db/ActiveRecord.php:435
#6  /project/vendor/yiisoft/yii2/db/ActiveRecord.php:469
#7  /project/vendor/yiisoft/yii2/db/BaseActiveRecord.php:500
#8  /project/vendor/yiisoft/yii2/db/BaseActiveRecord.php:315
#9  /project/protected/models/ar/Page.php:37
#10 /project/vendor/yiisoft/yii2/base/BaseObject.php:109
```
                                                              

This one seems a bit different :
```

36) WorkspacesCest: Test create
 Test  tests/functional/modules/api/user/WorkspacesCest.php:testCreate
                                                              
  [yii\base\ErrorException] Undefined index: constraint_name  
                                                              

Scenario Steps:

 5. $I->assertSame(0,0) at tests/functional/modules/api/user/WorkspacesCest.php:34
 4. $I->seeResponseCodeIs(422) at tests/functional/modules/api/user/WorkspacesCest.php:33
 3. $I->sendPUT("/api/user/2/workspaces/123123") at tests/functional/modules/api/user/WorkspacesCest.php:32
 2. $I->assertSame(0,0) at tests/functional/modules/api/user/WorkspacesCest.php:31
 1. $I->amLoggedInAs(2) at tests/functional/modules/api/user/WorkspacesCest.php:29

#1  /project/vendor/yiisoft/yii2/db/mysql/Schema.php:394
#2  /project/vendor/yiisoft/yii2/db/mysql/Schema.php:126
#3  /project/vendor/yiisoft/yii2/db/Schema.php:754
#4  /project/vendor/yiisoft/yii2/db/Schema.php:193
#5  /project/vendor/yiisoft/yii2/db/ActiveRecord.php:435
#6  /project/vendor/yiisoft/yii2/db/ActiveRecord.php:469
#7  /project/vendor/yiisoft/yii2/db/BaseActiveRecord.php:500
#8  /project/vendor/yiisoft/yii2/db/BaseActiveRecord.php:315
#9  /project/tests/_support/FunctionalTester.php:49
#10 /project/tests/functional/modules/api/user/WorkspacesCest.php:36
Artifacts:

Body: [
    {
        "field": "target_id",
        "message": "Target Id is invalid."
    }
]
Html: /project/tests/_output/prime.tests.functional.modules.api.user.WorkspacesCest.testCreate.fail.json
Response: /project/tests/_output/prime.tests.functional.modules.api.user.WorkspacesCest.testCreate.fail.json

```

**Comment by SamMousa** [comment]
I think it was fixed here: https://github.com/yiisoft/yii2/commit/f1aaa0de89c017d58afbd565d3ec3529fad6b4ea

You can try updating yii2 to dev-master.

**Comment by jeremiehelme** [comment]
Sorry, I had memory limit issues with php

So I've pulled your changes from master, and now have Yii 2.0.36 (checked in composer.lock and with Yii::getVersion();

I ran _docker-compose run --rm cli migrate_ and the 3 steps you mentioned before, just to be sure

unfortunately, still have the same issue when commiting

The messages seem all to be the same, and there is even more 
_(Tests: 155, Assertions: 254, Errors: 49, Skipped: 20, Incomplete: 3.)_


```
36) WorkspacesCest: Test create
 Test  tests/functional/modules/api/user/WorkspacesCest.php:testCreate
                                                              
  [yii\base\ErrorException] Undefined index: constraint_name  
                                                              

Scenario Steps:

 5. $I->assertSame(0,0) at tests/functional/modules/api/user/WorkspacesCest.php:34
 4. $I->seeResponseCodeIs(422) at tests/functional/modules/api/user/WorkspacesCest.php:33
 3. $I->sendPUT("/api/user/2/workspaces/123123") at tests/functional/modules/api/user/WorkspacesCest.php:32
 2. $I->assertSame(0,0) at tests/functional/modules/api/user/WorkspacesCest.php:31
 1. $I->amLoggedInAs(2) at tests/functional/modules/api/user/WorkspacesCest.php:29

#1  /project/vendor/yiisoft/yii2/db/mysql/Schema.php:394
#2  /project/vendor/yiisoft/yii2/db/mysql/Schema.php:126
#3  /project/vendor/yiisoft/yii2/db/Schema.php:757
#4  /project/vendor/yiisoft/yii2/db/Schema.php:193
#5  /project/vendor/yiisoft/yii2/db/ActiveRecord.php:435
#6  /project/vendor/yiisoft/yii2/db/ActiveRecord.php:469
#7  /project/vendor/yiisoft/yii2/db/BaseActiveRecord.php:500
#8  /project/vendor/yiisoft/yii2/db/BaseActiveRecord.php:315
#9  /project/tests/_support/FunctionalTester.php:49
#10 /project/tests/functional/modules/api/user/WorkspacesCest.php:36
Artifacts:

Body: [
    {
        "field": "target_id",
        "message": "Target Id is invalid."
    }
]
Html: /project/tests/_output/prime.tests.functional.modules.api.user.WorkspacesCest.testCreate.fail.json
Response: /project/tests/_output/prime.tests.functional.modules.api.user.WorkspacesCest.testCreate.fail.json
```

**Comment by SamMousa** [comment]
The commit I linked is NOT in that version.

**Comment by jeremiehelme** [comment]
Ok, I got it now, 
I needed to understand how to use the dev-master branch in composer

Thanks for your help and your time !
